# Generated by Django 5.2.10 on 2026-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_equipment', models.IntegerField()),
                ('average_flowrate', models.FloatField()),
                ('average_pressure', models.FloatField()),
                ('average_temperature', models.FloatField()),
                ('equipment_type_distribution', models.JSONField()),
            ],
        ),
    ]
